// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALQ1bv_ujT-YX7LG-LiMWx9zd4aCF_Zcc',
    appId: '1:929307024812:web:3fe7f5d420f7c93d76ee09',
    messagingSenderId: '929307024812',
    projectId: 'email-password-64698',
    authDomain: 'email-password-64698.firebaseapp.com',
    storageBucket: 'email-password-64698.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWdzlq9aJXDiVrx0y7ssToFAAIyylAJH8',
    appId: '1:929307024812:android:22f2faea510a415176ee09',
    messagingSenderId: '929307024812',
    projectId: 'email-password-64698',
    storageBucket: 'email-password-64698.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFcL7MFWQ7II5ibcVJjbe8YR8OG9_4-5g',
    appId: '1:929307024812:ios:6df66d8765bcae8376ee09',
    messagingSenderId: '929307024812',
    projectId: 'email-password-64698',
    storageBucket: 'email-password-64698.appspot.com',
    androidClientId: '929307024812-30l0n4b90uienhnb97a54vdauhqamknb.apps.googleusercontent.com',
    iosClientId: '929307024812-9rae0rel0r68hl0qvh4n40lvku6m5aij.apps.googleusercontent.com',
    iosBundleId: 'com.example.mytest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFcL7MFWQ7II5ibcVJjbe8YR8OG9_4-5g',
    appId: '1:929307024812:ios:6df66d8765bcae8376ee09',
    messagingSenderId: '929307024812',
    projectId: 'email-password-64698',
    storageBucket: 'email-password-64698.appspot.com',
    androidClientId: '929307024812-30l0n4b90uienhnb97a54vdauhqamknb.apps.googleusercontent.com',
    iosClientId: '929307024812-9rae0rel0r68hl0qvh4n40lvku6m5aij.apps.googleusercontent.com',
    iosBundleId: 'com.example.mytest',
  );
}
